services:
    configuration:
        class: Disqontrol\Configuration\Configuration
        arguments:
            - %configuration%

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
            - '@service_container'

    disqontrol.command.list_queues:
        class: Disqontrol\Console\Command\ListQueuesCommand
        arguments:
            - '@configuration'
        tags:
            - { name: disqontrol.command }

    logger:
        class: Monolog\Logger
        arguments:
            - 'disqontrol'

    disque_client_factory:
        class: Disqontrol\DisqueClientFactory
        arguments:
            - '@configuration'

    disque:
        class: Disque\Client
        factory:
            - '@disque_client_factory'
            - getClient

    job_factory:
        class: Disqontrol\Job\JobFactory

    job_serializer:
        class: Disqontrol\Job\Serializer\JsonSerializer

    job_marshaller:
        class: Disqontrol\Job\Marshaller\JobMarshaller
        arguments:
            - '@job_factory'
            - '@job_serializer'

    producer:
        class: Disqontrol\Producer\Producer
        arguments:
            - '@disque'
            - '@job_marshaller'
            - '@configuration'
            - '@logger'
            - '@event_dispatcher'

